#ifndef GUARD_CODE_0802688C_H
#define GUARD_CODE_0802688C_H

#include "global.h"

void LoadObjects_World1Select(void);
void LoadObjects_World2Select(void);
void LoadObjects_World3Select(void);
void LoadObjects_World4Select(void);
void LoadObjects_World5Select(void);
void sub_08028104(void);
void LoadObjects_World1Level1(void);
void LoadObjects_World1Level2(void);
void LoadObjects_World1Level3(void);
void LoadObjects_World1Level4(void);
void LoadObjects_World1Level5(void);
void LoadObjects_World1Level6(void);
void LoadObjects_World1Level7(void);
void LoadObjects_World1Boss(void);
void LoadObjects_World2Level1(void);
void LoadObjects_World2Level2(void);
void LoadObjects_World2Level3(void);
void LoadObjects_World2Level4(void);
void LoadObjects_World2Level5(void);
void LoadObjects_World2Level6(void);
void LoadObjects_World2Level7(void);
void LoadObjects_World2Boss(void);
void LoadObjects_World3Level1(void);
void LoadObjects_World3Level2(void);
void LoadObjects_World3Level3(void);
void LoadObjects_World3Level4(void);
void LoadObjects_World3Level5(void);
void LoadObjects_World3Level6(void);
void LoadObjects_World3Level7(void);
void LoadObjects_World3Boss(void);
void LoadObjects_World4Level1(void);
void LoadObjects_World4Level2(void);
void LoadObjects_World4Level3(void);
void LoadObjects_World4Level4(void);
void LoadObjects_World4Level5(void);
void LoadObjects_World4Level6(void);
void LoadObjects_World4Level7(void);
void LoadObjects_World4Boss(void);
void LoadObjects_World5Level1(void);
void LoadObjects_World5Level2(void);
void LoadObjects_World5Level3(void);
void LoadObjects_World5Level4(void);
void LoadObjects_World5Level5(void);
void LoadObjects_World5Level6(void);
void LoadObjects_World5Level7(void);
void LoadObjects_World5Boss(void);
void sub_080375A0(void);
void sub_08037DD4(void);
void sub_0803881C(void);
void sub_080392A4(void);
void LoadObjects_Common(void);

#endif // GUARD_CODE_0802688C_H