#ifndef GUARD_LOAD_ENTITY_GRAPHICS_H
#define GUARD_LOAD_ENTITY_GRAPHICS_H

#include "global.h"

void LoadEntityGraphics_World1Select(void);
void LoadEntityGraphics_World2Select(void);
void LoadEntityGraphics_World3Select(void);
void LoadEntityGraphics_World4Select(void);
void LoadEntityGraphics_World5Select(void);
void LoadEntityGraphics_World6Select_Unused(void);
void LoadEntityGraphics_World1Level1(void);
void LoadEntityGraphics_World1Level2(void);
void LoadEntityGraphics_World1Level3(void);
void LoadEntityGraphics_World1Level4(void);
void LoadEntityGraphics_World1Level5(void);
void LoadEntityGraphics_World1Level6(void);
void LoadEntityGraphics_World1Level7(void);
void LoadEntityGraphics_World1Boss(void);
void LoadEntityGraphics_World2Level1(void);
void LoadEntityGraphics_World2Level2(void);
void LoadEntityGraphics_World2Level3(void);
void LoadEntityGraphics_World2Level4(void);
void LoadEntityGraphics_World2Level5(void);
void LoadEntityGraphics_World2Level6(void);
void LoadEntityGraphics_World2Level7(void);
void LoadEntityGraphics_World2Boss(void);
void LoadEntityGraphics_World3Level1(void);
void LoadEntityGraphics_World3Level2(void);
void LoadEntityGraphics_World3Level3(void);
void LoadEntityGraphics_World3Level4(void);
void LoadEntityGraphics_World3Level5(void);
void LoadEntityGraphics_World3Level6(void);
void LoadEntityGraphics_World3Level7(void);
void LoadEntityGraphics_World3Boss(void);
void LoadEntityGraphics_World4Level1(void);
void LoadEntityGraphics_World4Level2(void);
void LoadEntityGraphics_World4Level3(void);
void LoadEntityGraphics_World4Level4(void);
void LoadEntityGraphics_World4Level5(void);
void LoadEntityGraphics_World4Level6(void);
void LoadEntityGraphics_World4Level7(void);
void LoadEntityGraphics_World4Boss(void);
void LoadEntityGraphics_World5Level1(void);
void LoadEntityGraphics_World5Level2(void);
void LoadEntityGraphics_World5Level3(void);
void LoadEntityGraphics_World5Level4(void);
void LoadEntityGraphics_World5Level5(void);
void LoadEntityGraphics_World5Level6(void);
void LoadEntityGraphics_World5Level7(void);
void LoadEntityGraphics_World5Boss(void);
void LoadEntityGraphics_Ex1(void);
void LoadEntityGraphics_Ex2(void);
void LoadEntityGraphics_Ex3(void);
void LoadEntityGraphics_FinalBoss(void);
void LoadEntityGraphics_Common(void);

#endif // LOAD_ENTITY_GRAPHICS